spring:
  application:
    name: mcp-server-generic
server:
  port: 8080

integrations:
  gmail:
    enabled: false
    base-url: https://gmail.googleapis.com/gmail/v1
    user-id: me
    access-token: ""
  market:
    enabled: false
    base-url: ""
    quote-path: /mcp/tools/market.quote
    auth-token: ""
  news:
    enabled: true
    connect-timeout-ms: 8000
    read-timeout-ms: 15000
    max-retries: 2
    max-concurrent-sources: 4
    blocked-hosts:
      - pinterest.com
      - instagram.com
      - facebook.com
    sources:
      - id: bbc
        url: https://feeds.bbci.co.uk/news/world/rss.xml
        type: RSS
        enabled: true
        auth: NONE
      - id: toi
        url: https://timesofindia.indiatimes.com/rssfeedstopstories.cms
        type: RSS
        enabled: true
        auth: NONE
      - id: github
        url: https://api.github.com/search/repositories
        type: JSON
        enabled: true
        auth: HEADER
        auth-header: Authorization
        auth-token: ""
        query-param: q
      - id: al-jazeera
        url: https://www.aljazeera.com/xml/rss/all.xml
        type: RSS
        enabled: true
        auth: BEARER
        auth-token: ""
        query-param: q
      - id: hacker-news
        url: https://news.ycombinator.com/rss
        type: RSS
        enabled: true
        auth: BEARER
        auth-token: ""
        query-param: q
      - id: pragmatic-engineer
        url: https://blog.pragmaticengineer.com/rss/
        type: RSS
        enabled: true
        auth: BEARER
        auth-token: ""
        query-param: q
      - id: google-search
        url: http://googleresearch.blogspot.com/atom.xml
        type: RSS
        enabled: true
        auth: BEARER
        auth-token: ""
        query-param: q
      - id: info-q
        url: https://feed.infoq.com
        type: RSS
        enabled: true
        auth: BEARER
        auth-token: ""
        query-param: q


mcp:
  api:
    auth:
      token: dev-token
